# Generated by Django 3.2.25 on 2024-05-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdet',
            fields=[
                ('userid', models.AutoField(db_column='iduserdet', primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='userdetnme', max_length=100)),
                ('useremail', models.IntegerField(db_column='userdeteml')),
                ('userpass', models.IntegerField(db_column='userdetpas')),
            ],
            options={
                'db_table': 'userdet',
                'managed': False,
            },
        ),
    ]
