# Generated by Django 3.2.25 on 2024-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expdet',
            fields=[
                ('expid', models.AutoField(db_column='idexpdet', primary_key=True, serialize=False, unique=True)),
                ('idreport', models.CharField(db_column='idrep', max_length=100)),
                ('expuname', models.CharField(db_column='expdetuname', max_length=100)),
                ('expcat', models.CharField(db_column='expdetcat', max_length=100)),
                ('expdes', models.CharField(db_column='expdetdes', max_length=100)),
                ('expdate', models.DateField(db_column='expdetdate')),
                ('expamt', models.IntegerField(db_column='expdetamt')),
            ],
            options={
                'db_table': 'expdet',
                'managed': False,
            },
        ),
    ]
